name: gql_phoenix_link
description: A graphql link using phoenix sockets
version: 0.2.1
homepage: https://github.com/knaeckeKami/gql_phoenix_link

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  phoenix_socket: ^0.6.4
  gql_exec: ^1.0.0
  gql_link: ^1.0.0

dev_dependencies:
  flutter_lints: ^1.0.4
  test: ^1.20.1
